apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment
  labels:
    app: express-depl
spec:
  selector:
    matchLabels:
      app: express-pod
  template:
    metadata:
      labels:
        app: express-pod
    spec:
      containers:
      - name: express-container
        image: gyan-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        env:
          - name: MONGO_URI
            value: mongodb://mongodb-service:27017/Gyan
          - name: PORT
            value: "5000"
          - name: JWT_SECRET
            value: thisisarandomstring

---

apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express-pod
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500

---
