apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: react-depl
spec:
  selector:
    matchLabels:
      app: react-pod
  template:
    metadata:
      labels:
        app: react-pod
    spec:
      containers:
      - name: react-container
        image: gyan-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173

---

apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-pod
  type: LoadBalancer
  ports:
  - port: 5173
    targetPort: 5173
    nodePort: 30517

---

